# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For PRs.

name: Build and Test

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

env:
  # See supported Node.js release schedule at https://nodejs.org/en/about/releases
  NODE_VERSION: 22.x

jobs:
  generateConfig:
    name: Generate Config
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - name: Generate dummy config
        run: npm run generate:config
        env:
          COLAB_EXTENSION_ENVIRONMENT: "production"
          COLAB_EXTENSION_CLIENT_ID: "client-id"
          COLAB_EXTENSION_CLIENT_NOT_SO_SECRET: "client-not-so-secret"
      - name: Upload generated config
        uses: actions/upload-artifact@v4
        with:
          name: generated-config
          path: src/colab-config.ts
          if-no-files-found: error

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: generateConfig
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - name: Download generated config
        uses: actions/download-artifact@v4
        with:
          name: generated-config
          path: src
      - run: npm run lint
      - run: npm run format:check
      - run: npm run typecheck
      # While spell check runs in lint, here we run it as a separate step to
      # make it easier to see the results and treat violations as errors
      # instead of warnings.
      - name: Spell Check
        run: npx cspell "**" --no-progress --show-suggestions --show-context --exclude "src/jupyter/client/generated/**" --exclude "src/jupyter/client/api.yaml"
